Improve health check for Local Integration Test and ensure proper cleanup of Docker containers

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -361,7 +361,6 @@ jobs:
         # Pull image
         REP_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
         IMAGE_NAME=ghcr.io/${REP_OWNER}/urlshortener:latest
-
         docker pull ${IMAGE_NAME}
 
         # start db container
@@ -370,5 +369,12 @@ jobs:
         # Wait for the application to start up
         sleep 15
 
-    - name: Wait for App to be healthy & exit
-      run: timeout 60s bash -c 'until [ "$(docker inspect -f {{.State.Health.Status}} urlshortener-app)" == "healthy" ]; do sleep 2; done' || (docker compose logs app && exit 1)
+        # Perform a health check to verify the application is running
+        if ! curl -f http://localhost:8080/actuator/health; then
+          echo "ERROR: Application is not running. Container-Logs:"
+          docker compose logs app
+          exit 1
+        fi
+
+        # Cleanup
+        docker compose down
